In [71]:
import os
from openpyxl import load_workbook
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [72]:
def readData():
    #Hack to get path of Notebook (Data file is in same directory structure)
    current_folder = globals()['_dh'][0]
    # Calculating path to the test data
    data_location = os.path.join(current_folder,'..' ,'data' , 'data_gen.xlsx')
    data_location = os.path.normpath(data_location)

    wb = load_workbook(data_location, data_only=True)
    ws=wb['data']

    data={'x':[], 'y':[]}
    cur_row=2

    while ws['A'+str(cur_row)].value != None:
        data['x'].append(ws['A'+str(cur_row)].value)
        data['y'].append(ws['B'+str(cur_row)].value)
        cur_row += 1
    df = pd.DataFrame(data)
    train, test =  train_test_split(df, test_size=0.2)
    return train, test

In [73]:
train, test=readData()

In [74]:
train

       x           y
454  454   59.223382
987  987  212.834195
485  485   65.045194
972  972  206.957189
228  228   28.396891
741  741  127.816496
771  771  136.888508
359  359   43.776344
869  869  169.032548
149  149   22.440260
690  690  113.220276
201  201   26.080280
205  205   26.405082
833  833  156.778133
567  567   82.298027
694  694  114.327478
923  923  188.386169
913  913  184.714165
507  507   69.410003
867  867  168.338147
38    38   18.288815
545  545   77.405218
244  244   29.907298
127  127   21.225851
702  702  116.561081
493  493   66.609997
310  310   37.220124
929  929  190.608572
530  530   74.180212
556  556   79.827422
..   ...         ...
566  566   82.071426
746  746  129.303498
785  785  141.245314
611  611   92.664444
130  130   21.380052
140  140   21.920056
726  726  123.415490
243  243   29.809897
23    23   18.105809
52    52   18.540821
368  368   45.084947
853  853  163.522141
221  221   27.768288
222  222   27.856889
527  527   73.546011
30    30   18.180012
897  897  178.922159
305  305   36.605122
418  418   52.944967
606  606   91.447442
612  612   92.909045
179  179   24.408272
291  291   34.936316
192  192   25.372877
153  153   22.681861
636  636   98.899454
983  983  211.258193
442  442   57.072977
980  980  210.080392
602  602   90.481041

[800 rows x 2 columns]

In [70]:
test

       x           y
678  678  109.937071
154  154   22.743262
676  676  109.395470
52    52   18.540821
498  498   67.600999
106  106   20.247242
1      1   18.000200
258  258   31.312903
339  339   40.984336
821  821  152.808528
754  754  131.703502
683  683  111.298073
271  271   32.688308
478  478   63.696991
740  740  127.520296
404  404   50.643362
45    45   18.405018
3      3   18.001801
287  287   34.473915
901  901  180.360560
663  663  105.914065
48    48   18.460819
900  900  180.000360
777  777  138.746111
866  866  167.991546
646  646  101.463458
179  179   24.408272
15    15   18.045006
312  312   37.468925
629  629   97.128452
..   ...         ...
333  333   40.177933
214  214   27.159286
101  101   20.040240
358  358   43.632943
973  973  207.346189
662  662  105.649065
952  952  199.261181
167  167   23.577867
562  562   81.169025
938  938  193.969175
734  734  125.751494
515  515   71.045206
460  460   60.320184
484  484   64.851394
965  965  204.245386
732  732  125.165093
47    47   18.441819
672  672  108.317069
378  378   46.576951
328  328   39.516931
352  352   42.780941
134  134   21.591254
679  679  110.208472
761  761  133.824504
575  575   84.125230
715  715  120.245286
968  968  205.405187
475  475   63.125190
231  231   28.672292
86    86   19.479234

[201 rows x 2 columns]